### ISSUE TITLE
Question: Number of goroutines.

### ISSUE THREAD

**Issue by thbaja** [garyburd/gary.burd.info#3]
Hi Gary, great example. Thanks.

I just wondered about this line of text:
"The application runs one goroutine for the hub and two goroutines for each connection."

But it seems that there is only two goroutines running; one for the hub and one for the connection writer. Or am I  missing something?

**Comment by garyburd** [comment]
The connection reader runs in a goroutine created by the HTTP server.

**Comment by thbaja** [comment]
Thanks for the reply. 

But I still don't get it when looking at these lines in `conn.go` in `ServerHTTP`:
```
go c.writer()
c.reader()
```

**Comment by garyburd** [comment]
The HTTP server [creates a goroutine for each client connection](https://github.com/golang/go/blob/2e4b6599541a92b76857ca546679a8d304730b10/src/net/http/server.go#L1843).  The function [wsHandler.ServeHTTP](https://github.com/garyburd/gary.burd.info/blob/a0d468ee549a6ec909f42a6748797fc6c676ed1c/go-websocket-chat/conn.go#L46) and everything called by wsHandler.ServeHTTP runs in that goroutine.

**Comment by thbaja** [comment]
Ok, thank you for the clarification and the exact links to the code. Very helpful!
